server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  session:
    redis:
      namespace: claksion:session
    store-type: redis
    timeout: 18000
  data:
    redis:
      host: localhost
      port: 6379
      password: aaaaa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sb2.cvsae4w4e5vl.ap-northeast-2.rds.amazonaws.com:3306/claksion?characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: ENC(8zHAipN8VZRabgMYzlv+aQ==)
    password: ENC(pMfm/sTsuKdwEahE+DIoXqThtaSKXXdG)
mybatis:
  type-aliases-package: com.claksion.app.data.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: info
app:
  url:
    serverurl: http://127.0.0.1:80
    server-url: http://localhost:80
  key:
    encrypt-key: claksionkey
    encrypt-algorithm: PBEWithMD5AndDES
  oauth:
    kakao:
      rest-api-key: 525aa8be9e038a0dccd36d35dca909d8
    naver:
      client-id: Dh_4f4_hl3mf8uj6nEDr
      client-secret-key: Z0Q_iVBEoH









  # /root/logs/